# mkdocs.yml
site_name: pygoodwe
theme:
  name: "material"

site_url: https://yaleman.github.io/pygoodwe/
repo_name: 'yaleman/pygoodwe'
repo_url: 'https://github.com/yaleman/pygoodwe'

plugins:
- search:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    watch:
    - "pygoodwe/"

nav:
  - "Home": README.md
  - "API Documentation": pygoodwe.md
  - Changelog: CHANGELOG.md
  - Releasing: release.md
