name: test the things

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # - name: Set up Python 3
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8
      # - name: Install dependencies
      #   run: python3 -m pip install --upgrade pip;
      #     python3 -m pip install flake8 pytest pylint;
      #     python3 -m pip install -r requirements.txt;

      # - name: Running pytest
      #   uses: fylein/python-pytest-github-action@v2
      #   with:
      #     args: python3 -m venv venv && source venv/bin/activate && python3 -m pip install -r requirements.txt  && python3 -m pytest test.py

      - name: Running pylint
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 -m pip install -r requirements.txt
            python3 -m pip install -r requirements-dev.txt
            python3 -m pylint --rcfile=.pylintrc pygoodwe

